### ISSUE TITLE
Unable to auth to JIRA

### ISSUE THREAD

**Issue by rickheil** [rustedgrail/hubot-jira#1]
Added the env variables for username and password and getting a 401 error from JIRA when the hubot starts up.

Console says:
[Tue Feb 24 2015 14:05:55 GMT-0500 (EST)] ERROR SyntaxError: Unexpected token <
  at Object.parse (native)
  at /opt/myhubot/node_modules/hubot-jira/src/jira-issues.coffee:44:7, <js>:18:19
  at IncomingMessage.<anonymous> (/opt/myhubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:80:22)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)

I've tripled checked the JIRA_URL and it is correct. Going to jiraUrl/rest/api/2/project in my browser does show the expected JSON output. Did I miss a step somewhere? Thanks for any pointers you might be able to give.

**Comment by rickheil** [comment]
PEBKAC here... one letter missing on my password. Sorry about the false alarm!
