### ISSUE TITLE
Syntax Error Unexpected token 

### ISSUE THREAD

**Issue by qk4l** [rustedgrail/hubot-jira#3]
Hi, I tried to use hubot-jira with rocketchat adapter but getting syntax error.

```
hubot_1       | hubot-jira@1.0.2 node_modules/hubot-jira
hubot_1       | └── coffee-script@1.6.3
...
hubot_1       | [Fri Aug 19 2016 17:40:10 GMT+0000 (UTC)] ERROR SyntaxError: Unexpected token <
hubot_1       |   at Object.parse (native)
hubot_1       |   at /home/hubot/node_modules/hubot-jira/src/jira-issues.coffee:43:7, <js>:17:19
hubot_1       |   at IncomingMessage.<anonymous> (/home/hubot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
hubot_1       |   at IncomingMessage.emit (events.js:129:20)
hubot_1       |   at _stream_readable.js:908:16
hubot_1       |   at process._tickCallback (node.js:355:11)
```

It does not seems as specific adapter issue.

**Comment by qk4l** [comment]
The problem was HUBOT_JIRA_PASSWORD which started with ':' symbol.

**Comment by rustedgrail** [comment]
The fastest solution would be to use a different password. We've removed this plugin from our hubot, because hipchat added it's own support for jira. If you want to open a PR, I'll be sure to review it quickly. Here is where the auth is happening.

https://github.com/rustedgrail/hubot-jira/blob/master/src/jira-issues.coffee#L34

**Comment by qk4l** [comment]
Ok. Could I also change output format in my PR to this one?

[KEY-3](https://github.com/rustedgrail/hubot-jira/issues/3): `In Progress` Summary
Type: Task, Priority: Normal, Assignee: Bob, Reporter: Grey
